name: asynji_sdk
description: A sdk for asynji.
version: 1.0.1
homepage: https://github.com/Reglament989/asynji-sdk

publish_to: https://pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  hive_generator: ^1.0.1
  build_runner: ^1.12.2
  mockito: ^5.0.5
  flutter_test:
    sdk: flutter
dependencies:
  dio: ^4.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  flutter:
    sdk: flutter
  web_socket_channel: ^2.0.0
